package com.main.utilities.helpers;

public enum KEYS {
    SYSTEM, ENVIRONMENT, TEST_SUITE, PROJECT_PATH, TEST_RESOURCES, REPORT_PATH, OS_NAME, STANDALONE_SERVER_PATH, REMOTEWEBDRIVER_BROWSERS, PROPERTY_FILE_PATH;
}